# Generated by Django 6.0.3 on 2026-04-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_reference', models.CharField(db_index=True, help_text='Identifiant logique/unique fourni par la banque pour éviter les doublons', max_length=255)),
                ('bank_date', models.DateField(help_text="Date réelle de l'opération bancaire")),
                ('bank_label', models.CharField(help_text="Le libellé brut (ex: 'CB CARREFOUR TOULOUSE')", max_length=255)),
                ('bank_category', models.CharField(blank=True, help_text='La catégorie automatique donnée par la banque', max_length=100, null=True)),
                ('bank_amount', models.DecimalField(decimal_places=2, help_text='Le montant réel prélevé ou viré par la banque', max_digits=10)),
                ('custom_date', models.DateField(help_text='Date sur laquelle tu souhaites imputer cette ligne (par défaut égale à bank_date)')),
                ('custom_amount', models.DecimalField(decimal_places=2, help_text='Le montant que tu comptes réellement. Modifiable pour diviser une dépense.', max_digits=10)),
                ('comment', models.TextField(blank=True, help_text='Un petit mot pour se souvenir du pourquoi du comment', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Permet de savoir si tu as déjà validé/catégorisé cette ligne')),
                ('category', models.ForeignKey(blank=True, help_text='Votre catégorie personnalisée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneymanager.category')),
            ],
            options={
                'ordering': ['-bank_date'],
            },
        ),
    ]
