# Generated by Django 6.0.3 on 2026-04-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0002_owner_transaction_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, help_text="L'enveloppe prévue pour ce mois", max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='moneymanager.owner')),
            ],
            options={
                'ordering': ['-year', '-month', 'category__name'],
                'unique_together': {('owner', 'category', 'year', 'month')},
            },
        ),
    ]
