# Generated by Django 6.0.3 on 2026-04-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0003_monthlybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Budget de base par défaut', max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_budgets', to='moneymanager.owner')),
            ],
            options={
                'ordering': ['category__name'],
                'unique_together': {('owner', 'category')},
            },
        ),
    ]
