# Generated by Django 6.0.3 on 2026-04-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0004_defaultbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text="L'argent total actuel en banque", max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_balance', to='moneymanager.owner')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Big voyage, Sécurité, Holidays 2025', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant alloué (peut être négatif pour une avance)', max_digits=10)),
                ('comment', models.CharField(blank=True, help_text='Notes (Ex: RTX)', max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_envelopes', to='moneymanager.owner')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
