# Generated by Django 6.0.3 on 2026-04-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0005_accountbalance_globalenvelope'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEnvelopeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('PROVISION', "Provision (Épargne) : Une dépense (-) AJOUTE de l'argent à l'enveloppe (+)"), ('EXPENSE', "Consommation (Dépense réelle) : Une dépense (-) RETIRE de l'argent de l'enveloppe (-)")], default='EXPENSE', help_text="Détermine comment la transaction impacte l'enveloppe.", max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.category')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.globalenvelope')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_links', to='moneymanager.owner')),
            ],
            options={
                'unique_together': {('owner', 'category')},
            },
        ),
    ]
