# Generated by Django 6.0.3 on 2026-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0006_categoryenvelopelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='purple', help_text='Couleur de base (ex: blue, green, red, yellow, pink, indigo)', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='📁', help_text='Émoji pour identifier la catégorie', max_length=5),
        ),
    ]
