# Generated by Django 6.0.3 on 2026-05-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0008_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Ex: LECLERC, NETFLIX, EDF...', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rules', to='moneymanager.owner')),
            ],
            options={
                'verbose_name': 'Règle de tri auto',
                'verbose_name_plural': 'Règles de tri auto',
                'unique_together': {('owner', 'keyword', 'category')},
            },
        ),
    ]
