# Generated by Django 6.0.3 on 2026-05-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0009_autocategoryrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour une catégorie commune. Remplir pour une catégorie privée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='moneymanager.owner'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='📁', max_length=20),
        ),
    ]
