# Generated by Django 6.0.3 on 2026-05-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0010_alter_category_options_category_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalenvelope',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Objectif à atteindre (Optionnel)', max_digits=10, null=True),
        ),
    ]
